### ISSUE TITLE
wrong license

### ISSUE THREAD

**Issue by skasberger** [ginseng666/GeoJSON-TopoJSON-Austria#1]
mit is a software license and does not apply properly to data. for data, public domain / cc zero or ODBL are recommended. but be aware, you must have full ownership of the data yourself, so you can offer it under a free license to others.

**Comment by ginseng666** [comment]
thx for the info - well, can i offer it under a cc licence if the source material itself was under cc by 3.0?

**Comment by skasberger** [comment]
sure. but copyright holder then stays the same, if you have not changed anything. if you have changed, you just have to make attribution to the original source/copyright holder.
