### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by pkolmann** [ginseng666/GeoJSON-TopoJSON-Austria#5]
Hi,

I have discovered a few spelling errors in the 2017 Gemeinde file:

* name": "Fallizien", "iso": "20806" --> proper name is Gallizien (https://de.wikipedia.org/wiki/Gallizien)
* "name": "St. Gallenkirc", "iso": "80120"  --> proper name is St. Gallenkirch (https://de.wikipedia.org/wiki/St._Gallenkirch)

I am not sure how you generate those files, but maybe you could fix those mistakes.
Thanks Philipp

**Comment by ginseng666** [comment]
Thanks for the sharp eye, should be fixed now.
