### ISSUE TITLE
More spelling Mistakes

### ISSUE THREAD

**Issue by pkolmann** [ginseng666/GeoJSON-TopoJSON-Austria#6]
Hi,

while working with your data for https://github.com/pkolmann/austria-post-and-aera-code I discovered more spelling issues:

"St. Gallenkirc"; // BUG: St. Gallenkirch
"Markt Sankt Martin"; /* BUG */
"St. Ruprech"; // BUG: 8181 St. Ruprecht
"Spita"; // BUG: Spital am Semmering
"Altenmark"; // BUG: "Altenmarkt";
"St. Georgen am Längssee"; // BUG: St. Georgen am Längsee
"Klein Sankt Paul"; //BUG: Klein St. Paul
"Bad Sankt Leonhard im Lavanttal"; // BUG: Bad St. Leonhard im Lavanttal

Thanks
Philipp

**Comment by ginseng666** [comment]
Thanks, the issues should be fixed now, I also corrected/changed a lot of names to match the official spelling.
