### ISSUE TITLE
Bezirksgrenzen für Wien

### ISSUE THREAD

**Issue by pkolmann** [ginseng666/GeoJSON-TopoJSON-Austria#7]
Hi,

would it be possible to add to the Beirke File the district borders within Vienna?

Currently Vienna has no district borders at all.

The data can be found here:

https://www.data.gv.at/katalog/dataset/stadt-wien_bezirksgrenzenwien

Thanks
Philipp

**Comment by ginseng666** [comment]
See the 2021-folder, hope this helps: https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/tree/master/2021
