### ISSUE TITLE
bezirke_995_topo.json contains Polygon for "Wien" / 900

### ISSUE THREAD

**Issue by jfiala** [ginseng666/GeoJSON-TopoJSON-Austria#9]
2021\simplified-99.5\bezirke_995_topo.json

It contains a polygon for "Wien(Stadt)":
{"arcs":[[89,90,91,92,93,94,95,96,97,8,98,-71,-70,99,100]],"type":"Polygon","properties":{"name":"Wien(Stadt)","iso":"900"}}

This may cover other polygons below (e.g. Wien(Stadt) then overlaps Döbling).
After removing the polygon the map is shown correctly.

**Comment by ginseng666** [comment]
This is intentional (see readme) as sometimes one might want to display Vienna as a whole, sometimes as districts (as data might only be available for the whole city). The features not needed can be filtered/removed before use.

**Comment by jfiala** [comment]
Alright, thank you for the comment.
